# Welcome to Jekyll!

# Website settings
title: "James"
description: "James's portfolio."
keywords: "james,fobid,portfolio,github,gh-pages"
baseurl: "/"
url: "https://fobidlim.github.io"

# author
author:
  name: 'James'
  first_name: 'Sungtae'
  last_name: 'Lim'
  email: 'fobidlim@gmail.com'
  instagram_username: 'fobidlim'
  facebook_username: 'fobidlim'
  github_username: 'fobid'
  linkedin_username: 'fobid'
  avatar: 'static/img/landing/James.jpg'
  desc: 'Android application 을 개발하고 있습니다. ReactiveX(Rx) 기술을 좋아하고, Open Source 에 관심이 많습니다. Clean code를 항상 고민합니다. 인생은 배움의 연속이라고 생각합니다. 배움을 통하여 이를 숙달하기 까지 많은 연습을 하고 있습니다. 그렇기 때문인지 숙련이 필요한 Skateboard, DJing이 취미이며, 최근에는 영상 제작도 취미로 하고있습니다.'

# comment
# changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
# disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
# bshare:
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
# ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-102318557-1

# growingIO
# gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
